#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  pull_request:
    paths-ignore:
      - "ts/**"
  push:
    branches:
      - "main"
    paths-ignore:
      - "ts/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-main-build:
    name: Build main extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      ci_tools_version: main
      duckdb_version: main
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      extension_name: ui

  duckdb-next-patch-build:
    name: Build next patch extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.0
    with:
      ci_tools_version: v1.3.0
      duckdb_version: v1.3-ossivalis
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      extension_name: ui

  duckdb-stable-build:
    name: Build stable extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.0
    with:
      ci_tools_version: v1.3.0
      duckdb_version: v1.3.0
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      extension_name: ui

  duckdb-stable-deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
    name: Deploy stable extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.3.0
    secrets: inherit
    with:
      extension_name: ui
      ci_tools_version: v1.3.0
      duckdb_version: v1.3.0
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}